services:
  dashboard-backend:
    # Use host network mode for backend if needed
    network_mode: host
    ports:
      - 3003:3003
    volumes:
      - ./datasets:/usr/src/app/datasets
      - ./server/uploads/:/usr/src/app/uploads
    image: dashboard-backend
    restart: unless-stopped
    user: "${UID}:${GID}"

  dashboard:
    ports:
      - 5173:5173
    image: dashboard
    restart: unless-stopped

  #trainer:
    #ports: 3333:3333
    #  - 
    #volumes:
    #  - ./datasets:/workspace/datasets
    #  - ./models:/workspace/models
