services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: unless-stopped

  dashboard-backend:
    depends_on:
      - redis
    image: dashboard-backend
    network_mode: host
    ports:
      - 3003:3003
    volumes:
      - ./datasets:/usr/src/app/datasets
      - ./models:/usr/src/app/models
      - ./server/uploads/:/usr/src/app/uploads
    restart: unless-stopped
    user: "${UID}:${GID}"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

  dashboard:
    image: dashboard
    ports:
      - 5173:5173
    restart: unless-stopped
