services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: unless-stopped

  dashboard-backend:
    network_mode: host
    image: dashboard-backend
    ports:
      - 3003:3003
    volumes:
      - ./datasets:/usr/src/app/datasets
      - ./server/uploads:/usr/src/app/uploads
      - /home/chunt/ComfyUI/output/putty-ai:/usr/src/app/output
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
      NODE_ENV: production
      REDIS_URL: redis://localhost:6379
    depends_on:
      - redis

  dashboard-worker:
    network_mode: host
    image: dashboard-worker
    shm_size: 64g
    volumes:
      - ./datasets:/usr/src/app/datasets
      - ./models:/usr/src/app/models
      - ./server/temp/:/usr/src/app/temp
      - /home/chunt/.triton/:/tmp/.triton
    restart: unless-stopped
    user: "${UID}:${GID}"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      REDIS_URL: redis://localhost:6379
      TRITON_CACHE_DIR: /tmp/.triton
    depends_on:
      - redis

  dashboard:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: dashboard
    ports:
      - 5173:5173
    restart: unless-stopped
