########
output_dir = ''
########
dataset = ''
########

epochs = 28

########
micro_batch_size_per_gpu = 1
########

pipeline_stages = 1
gradient_accumulation_steps = 1
gradient_clipping = 1.0
warmup_steps = 100
eval_every_n_epochs = 1
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1
save_every_n_epochs = 4
checkpoint_every_n_epochs = 30
activation_checkpointing = true
partition_method = 'parameters'
save_dtype = 'bfloat16'
caching_batch_size = 1
compile = true
steps_per_print = 1
[model]
type = 'sdxl'
checkpoint_path = ''
dtype = 'bfloat16'
min_snr_gamma = 5
debiased_estimation_loss = true
#unet_lr = 4e-5
#text_encoder_1_lr = 2e-5
#text_encoder_2_lr = 2e-5
[adapter]
type = 'lora'
rank = 32
dtype = 'bfloat16'
[optimizer]
type = 'Prodigy'
lr = 1
betas = [0.9, 0.99]
weight_decay = 0.01
[monitoring]
enable_wandb = false
wandb_api_key = ''
wandb_tracker_name = ''
wandb_run_name = ''
